# Generated by Django 4.2 on 2026-03-28 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='datasets/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('rows_count', models.IntegerField(blank=True, null=True)),
                ('columns_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('profiling', 'Profiling'), ('profiled', 'Profiled'), ('cleaning', 'Cleaning'), ('cleaned', 'Cleaned'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_info', models.JSONField()),
                ('missing_values', models.JSONField()),
                ('duplicates', models.JSONField()),
                ('outliers', models.JSONField()),
                ('data_types_issues', models.JSONField()),
                ('invalid_values', models.JSONField()),
                ('statistics', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='DataSentinel.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('missing', 'Missing Values'), ('duplicate', 'Duplicates'), ('outlier', 'Outliers'), ('type_mismatch', 'Type Mismatch'), ('invalid', 'Invalid Values')], max_length=20)),
                ('column_name', models.CharField(max_length=255)),
                ('affected_rows', models.JSONField()),
                ('issue_description', models.TextField()),
                ('recommended_action', models.CharField(choices=[('fill_mean', 'Fill with Mean'), ('fill_median', 'Fill with Median'), ('fill_mode', 'Fill with Mode'), ('fill_forward', 'Forward Fill'), ('fill_backward', 'Backward Fill'), ('drop_rows', 'Drop Rows'), ('drop_column', 'Drop Column'), ('remove_duplicates', 'Remove Duplicates'), ('cap_outliers', 'Cap Outliers'), ('remove_outliers', 'Remove Outliers'), ('convert_type', 'Convert Data Type'), ('replace_invalid', 'Replace Invalid Values')], max_length=50)),
                ('action_params', models.JSONField(blank=True, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='DataSentinel.dataprofile')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CleaningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(max_length=50)),
                ('column_name', models.CharField(max_length=255)),
                ('rows_affected', models.IntegerField()),
                ('details', models.JSONField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_logs', to='DataSentinel.dataset')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataSentinel.cleaningrecommendation')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataSentinel.dataset')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('summary', 'Summary Statistics'), ('correlation', 'Correlation Analysis'), ('distribution', 'Distribution Analysis'), ('trend', 'Trend Analysis'), ('kpi', 'KPI Analysis')], max_length=20)),
                ('result_data', models.JSONField()),
                ('visualizations', models.JSONField(blank=True, null=True)),
                ('insights', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='DataSentinel.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('file_path', models.FileField(upload_to='dataset_versions/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('rows_count', models.IntegerField()),
                ('columns_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='DataSentinel.dataset')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('dataset', 'version_number')},
            },
        ),
    ]
