# Generated by Django 4.2 on 2026-03-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataSentinel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaninglog',
            name='execution_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cleaninglog',
            name='status',
            field=models.CharField(default='success', max_length=20),
        ),
    ]
